Repository arajshow/Contribution_Repo, pull requests merged in 2022-10, with the labels that each got.

#10 Solution for the n Queen problem
  Important Questions/nQueen.cpp
Labels: Hactoberfest-accepted

#8 Create Cocktail Sort.cpp
  Sorting Techniques/Cocktail Sort.cpp
Labels: Hactoberfest-accepted

#15 Create reverse_Words_String.cpp
  Important Questions/reverse_Words_String.cpp
Labels: Hactoberfest-accepted

#16 Sticker Thief
  Important Questions/sticklerThief.cpp
Labels: Hactoberfest-accepted

#17 added files
  Searching_Techniques/Binary_search.cpp
  Searching_Techniques/Binary_search.exe
  Searching_Techniques/Depth_First_search.cpp
  Searching_Techniques/Depth_First_search.exe
Labels: Hactoberfest-accepted

#20 Added Trapping rain water problem solution
  Important Questions/TrappingRainWater.cpp
Labels: Hactoberfest-accepted

#21 Coin Change problem in Py3
  Important Questions/coinchange.py
Labels: Hactoberfest-accepted

#23 Container With Most Water
  Important Questions/ContainerMostWater.cpp
Labels: Hactoberfest-accepted

#24 Topological Sorting Code Added
  Sorting Techniques/Topological_Sort.cpp
Labels: Hactoberfest-accepted

#26 Create pyramid.cpp
  Pattern printing/pyramid.cpp
Labels: Hactoberfest-accepted

#27 added some important question of binary tree
  Binary Tree Questions/Check for Children Sum Property.cpp
  Binary Tree Questions/Check if Binary Tree is the mirror of itself or not.cpp
  Binary Tree Questions/Construct Binary Tree from Inorder and Postorder.cpp
  Binary Tree Questions/Construct Binary Tree from inorder and preorder.cpp
  Binary Tree Questions/Flatten Binary Tree to LinkedList.cpp
  Binary Tree Questions/Maximum path sum.cpp
  Binary Tree Questions/Ones and Zeroes.cpp
  Binary Tree Questions/Symmetric Binary Tree.cpp
Labels: Hactoberfest-accepted

#28 Create MaximumSumOfSubarray.cpp
  Important Questions/MaximumSumOfSubarray.cpp
Labels: Hactoberfest-accepted

#30 added new python projects:
  Python/Colorizing images ML/.idea/.gitignore
  Python/Colorizing images ML/.idea/Colorizing images ML.iml
  Python/Colorizing images ML/.idea/dbnavigator.xml
  Python/Colorizing images ML/.idea/inspectionProfiles/Project_Default.xml
  Python/Colorizing images ML/.idea/inspectionProfiles/profiles_settings.xml
  Python/Colorizing images ML/.idea/misc.xml
  Python/Colorizing images ML/.idea/modules.xml
  Python/Colorizing images ML/images/img1.jpg
  Python/Colorizing images ML/images/img2.jpg
  Python/Colorizing images ML/images/img3.jpg
  Python/Colorizing images ML/main.py
  Python/Colorizing images ML/model download urls.txt
  Python/GUI application for photo editing.py
Labels: Hactoberfest-accepted

#32 Create subsetsubprob.cpp
  Important Questions/subsetsubprob.cpp
Labels: Hactoberfest-accepted

#31 Important Queue questions added
  .DS_Store
  Queue Questions/BalancedParanthesis.cpp
  Queue Questions/PlayingWithCards.cpp
  Queue Questions/Qwith2Stack.cpp
  Queue Questions/ReverseAStackUsingRecursion.cpp
  Queue Questions/StackMin.cpp
  Queue Questions/StockSpan.cpp
  Queue Questions/histogramArea.cpp
  Queue Questions/nextgreater.cpp
Labels: Hactoberfest-accepted, Hacktoberfest

#35 Hackoctoberfest22
  Stack/balanced paranthesis using stack.cpp
  Stack/index
  Stack/recursivly reverse a stack.cpp
  Stack/reverse stack using 1 extra stack.cpp
  Stack/stack using STL.cpp
  Stack/stack using array.cpp
  Stack/stack using vector.cpp
  Stack/stock span problem.cpp
Labels: Hactoberfest-accepted, Hacktoberfest

#34 Added Left view tree
  Binary Tree Questions/LeftViewTree.cpp
Labels: Hactoberfest-accepted, Hacktoberfest

#36 Infix to postfix
  Binary Tree Questions/right_view_of_a_tree.cpp
  Stack/infix_to_postfix.cpp
Labels: Hactoberfest-accepted, Hacktoberfest

#37 Heap Sort.cpp added
  Sorting Techniques/Heap Sort.cpp
Labels: Hactoberfest-accepted, Hacktoberfest

#40 updated Html
  CSS/new.md
  html/contact.html
  html/dp.jpg
  html/form.html
  html/hobbie.html
  html/index.html
  html/skill_challenge.html
  html/styles.css
  html/table.html
Labels: good first issue
